"""OKF v0.1 format helpers: frontmatter, directory indexes, validate, zip.

Spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md

A bundle is a directory of markdown concept files with YAML frontmatter whose
only required field is `type`, plus reserved `index.md` (directory listing,
no frontmatter) and `log.md` (history) files. Every directory carries an
`index.md` so agents can navigate by progressive disclosure — the property
that made calknowledge bundles reliably navigable by independent agents.
"""

from __future__ import annotations

import zipfile
from collections import defaultdict
from pathlib import Path, PurePosixPath

import yaml

from .config import STATE_DIRNAME

RESERVED = {"index.md", "log.md"}


def frontmatter(fields: dict) -> str:
    """YAML frontmatter block; empty values are dropped."""
    clean = {k: v for k, v in fields.items() if v not in (None, "", [])}
    return "---\n" + yaml.safe_dump(clean, sort_keys=False, allow_unicode=True) + "---\n"


def dodge_reserved(rel: PurePosixPath) -> PurePosixPath:
    """Concept files must not use reserved names: .../index.md -> .../home.md."""
    if rel.name == "index.md":
        return rel.with_name("home.md")
    if rel.name == "log.md":
        return rel.with_name("history.md")
    return rel


def write_directory_indexes(bundle_dir: Path, entries: dict[PurePosixPath, str]) -> int:
    """Write an `index.md` listing in every directory that holds concepts, so
    agents descend the tree instead of guessing paths.

    entries: {bundle-relative concept path: display title}. The bundle root
    index is written separately (write_root_index).
    """
    dirs: dict[PurePosixPath, dict] = defaultdict(lambda: {"files": [], "dirs": set()})
    for rel, title in entries.items():
        dirs[rel.parent]["files"].append((rel, title))
        d = rel.parent
        while d != PurePosixPath("."):
            dirs[d.parent]["dirs"].add(d)
            d = d.parent

    written = 0
    for d, content in dirs.items():
        if d == PurePosixPath("."):
            continue
        lines = [f"# /{d} — directory listing", ""]
        for sub in sorted(content["dirs"]):
            lines.append(f"- [{sub.name}/](/{sub}/index.md)")
        for rel, title in sorted(content["files"]):
            lines.append(f"- [{title or rel.stem}](/{rel})")
        (bundle_dir / d / "index.md").write_text("\n".join(lines) + "\n", encoding="utf8")
        written += 1
    return written


def write_root_index(bundle_dir: Path, root_url: str | None, page_count: int) -> None:
    (bundle_dir / "index.md").write_text(
        f"# {root_url or 'Website'} — OKF knowledge bundle\n\n"
        f"Generated by okf-kit. Every directory has an index.md listing its contents.\n\n"
        f"- [pages/](/pages/index.md) — {page_count} pages (type: Web Page), "
        f"mirroring the site hierarchy\n",
        encoding="utf8",
    )


def validate_bundle(directory, *, quiet: bool = False) -> bool:
    """OKF v0.1 conformance: every non-reserved .md has parseable frontmatter
    with a non-empty `type`. The bundle's own state dir is skipped."""
    bundle_dir = Path(directory)
    if not bundle_dir.is_dir():
        if not quiet:
            print(f"not a directory: {directory}")
        return False

    errors: list[str] = []
    checked = 0
    for md_file in bundle_dir.rglob("*.md"):
        if STATE_DIRNAME in md_file.parts or md_file.name in RESERVED:
            continue
        checked += 1
        rel = md_file.relative_to(bundle_dir)
        text = md_file.read_text(encoding="utf8")
        if not text.startswith("---\n"):
            errors.append(f"{rel}: missing frontmatter")
            continue
        try:
            fm = yaml.safe_load(text[4 : text.index("\n---\n", 4)])
        except Exception as exc:  # noqa: BLE001
            errors.append(f"{rel}: unparseable frontmatter ({exc})")
            continue
        if not isinstance(fm, dict) or not str(fm.get("type") or "").strip():
            errors.append(f"{rel}: missing/empty required field 'type'")

    if not quiet:
        for err in errors[:20]:
            print(f"  ✗ {err}")
        verdict = "CONFORMANT" if not errors else "NOT CONFORMANT"
        print(f"Validation: {checked} concept files, {len(errors)} errors -> {verdict}")
    return not errors


def zip_bundle(directory, *, output=None) -> Path:
    """Package the bundle under a single top-level folder for hand-off.

    Excludes the internal state dir — the shipped artifact is pure OKF.
    """
    bundle_dir = Path(directory)
    if not (bundle_dir / "index.md").exists():
        raise SystemExit(f"{bundle_dir} is not an OKF bundle (no index.md)")
    root = bundle_dir.name
    zip_path = Path(output) if output else bundle_dir.parent / f"{root}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(bundle_dir.rglob("*")):
            if f.is_file() and STATE_DIRNAME not in f.relative_to(bundle_dir).parts:
                zf.write(f, str(PurePosixPath(root) / f.relative_to(bundle_dir)))
    size_mb = zip_path.stat().st_size / 1024 / 1024
    print(f"Wrote {zip_path} ({size_mb:.1f} MB)")
    return zip_path
